### ISSUE TITLE
Throw events when a danger or obstacle is detected

### ISSUE THREAD

**Issue by JonasPriest** [fred-project/fred#47]
Throw events when the sensor readings of the Control API assume that there is a danger or obstacle so that the business logic can react to that by adding them to the map environment

**Comment by MyRealityCoding** [comment]
We already check for the collision [here](https://github.com/fred-project/fred/blob/master/core/services/collision.py#L32), which basically does the following:

1. check the current distance to the nearest obstacle in front
2. if distance is smaller than 5 (just a value, can be modified, though) then collision is detected
3. collision will be updated as ```OBSTACLE_DYNAMIC``` type in our grid system

There is no mechanism for an event, though. We could support a collision listener to the collision service to enable additional behavior.
